import { Game, Review, Article } from './types';

export const GAMES: Game[] = [
  {
    id: '1',
    title: 'Neon Syndicate',
    description: 'Infiltrate the high-rise servers of the global megacorps. Your team is your only lifeline in this high-octane heist.',
    image: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?q=80&w=2070&auto=format&fit=crop',
    players: '2-4 Players',
    tags: ['Action', 'Heist', 'Cyberpunk'],
    category: 'Co-op Adventures',
    whyFun: 'The asymmetric hacking mechanics mean everyone has a unique role. No more "following the leader"—you win together or fail alone.',
  },
  {
    id: '2',
    title: 'Void Mariners',
    description: 'Manage a struggling starship through uncharted galaxies. Repair systems, manage fuel, and discover ancient alien relics.',
    image: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?q=80&w=1954&auto=format&fit=crop',
    players: '1-6 Players',
    tags: ['Space', 'Survival', 'Strategy'],
    category: 'Co-op Adventures',
    whyFun: 'Chaos management at its finest. Screaming at your friend to fix the oxygen while you pilot through an asteroid belt is peak bonding.',
  },
  {
    id: '3',
    title: 'Misfit Mayhem',
    description: 'The ultimate physics-based friendship destroyer. 50+ minigames designed to provoke maximum laughter and minimal strategy.',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2070&auto=format&fit=crop',
    players: '8+ Players',
    tags: ['Party', 'Physics', 'Mini-games'],
    category: 'Party Games',
  },
  {
    id: '4',
    title: "Liar's Deck",
    description: 'A social deduction card game where your voice is your only weapon. Deceive, bluff, and betray.',
    image: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?q=80&w=2070&auto=format&fit=crop',
    players: '3-8 Players',
    tags: ['Deduction', 'Social', 'Cards'],
    category: 'Party Games',
    length: '15 Min',
  },
  {
    id: '5',
    title: 'Doodle Duel',
    description: 'Collaborative art meets competitive guessing. The worse you draw, the funnier it gets.',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=2071&auto=format&fit=crop',
    players: '2-12 Players',
    tags: ['Drawing', 'Creative', 'Party'],
    category: 'Party Games',
    length: '20 Min',
  },
  {
    id: '6',
    title: 'Echoes of the Deep',
    description: 'Submarine exploration where sound is your only vision. Navigate treacherous trenches and avoid what lurks in the dark.',
    image: 'https://images.unsplash.com/photo-1583000292278-5951df340820?q=80&w=2071&auto=format&fit=crop',
    players: '2-4 Players',
    tags: ['Horror', 'Exploration', 'Co-op'],
    category: 'Co-op Adventures',
    whyFun: 'The sonar-based gameplay creates a unique tension. You have to trust your navigator completely while you pilot through narrow gaps.',
  },
  {
    id: '7',
    title: 'Kitchen Chaos',
    description: 'The ultimate culinary stress test. Prepare, cook, and serve dishes while the kitchen literally falls apart around you.',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=2070&auto=format&fit=crop',
    players: '1-4 Players',
    tags: ['Cooking', 'Simulation', 'Party'],
    category: 'Party Games',
    length: '10 Min',
  },
];

export const REVIEWS: Review[] = [
  {
    id: '1',
    author: 'Alex_Gamer24',
    avatar: 'https://i.pravatar.cc/150?u=alex',
    gameTitle: 'Starlight Odyssey',
    content: '"Hands down the best co-op experience I\'ve had in years. The way the mechanics force you to communicate without being frustrating is a masterclass in game design."',
    rating: 5,
    helpfulCount: '1.2K',
  },
  {
    id: '2',
    author: 'SarahPixel',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
    gameTitle: 'Neon Squad',
    content: '"The atmosphere in this game is incredible. It\'s rare to find a multiplayer game that feels this immersive. Great for those who love deep lore and tactical play."',
    rating: 4.5,
    helpfulCount: '840',
  },
  {
    id: '3',
    author: 'Devin_W',
    avatar: 'https://i.pravatar.cc/150?u=devin',
    gameTitle: 'Forge Masters',
    content: '"Finally, a crafting game that doesn\'t feel like a chore! Playing this with three friends is pure joy. Highly recommend for casual weekend gaming sessions."',
    rating: 5,
    helpfulCount: '2.1K',
  },
];

export const ARTICLES: Article[] = [
  {
    id: '1',
    title: 'The Rise of Social Gaming: Why Playing Together is the New Meta',
    excerpt: 'From pixelated couch co-ops to massive digital universes, the way we connect through games is undergoing a radical transformation.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=2070&auto=format&fit=crop',
    category: 'Editorial',
    date: 'May 20, 2024',
    readTime: '12 Min Read',
    author: 'Alex Rivers',
  },
  {
    id: '2',
    title: 'Top 5 Co-op Games for Your Next House Party',
    excerpt: 'Forget Monopoly. These modern masterpieces are designed to bring friends together.',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=2071&auto=format&fit=crop',
    category: 'Collections',
    date: 'May 15, 2024',
    readTime: '8 Min Read',
    author: 'Jamie Chen',
  },
  {
    id: '3',
    title: 'The Psychology of Cooperation: Why We Love Losing Together',
    excerpt: 'Exploring the bonding power of shared failure in high-stakes cooperative gaming environments.',
    image: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=2070&auto=format&fit=crop',
    category: 'Analysis',
    date: 'May 10, 2024',
    readTime: '15 Min Read',
    author: 'Dr. Elena Vance',
  },
];
